<!DOCTYPE html>
<html lang="ja">
<?php include(__DIR__."/common/head.html"); ?>
  <body>
<?php include(__DIR__."/common/header.html"); ?>
  <div class="container">
    <div class="col-md-8 col-md-offset-2 white-box">
      <div class="row buffer buffer-side">
        <h4>コメント投稿内容の確認</h4>
        <hr></hr>
      </div>
      <div class="row buffer-side buffer">
        <p><?php if(empty($params['name'])){echo "匿名";}else{echo htmlspecialchars($params['name']);} ?></p>
        <div><?php echo htmlspecialchars($params['comment'])?></div>
        <?php if(isset($params['save_file_name'])){ ?>
          <img src="/uploads/tmp/<?php echo $params['save_file_name']?>" width="200"></img>
        <?php } ?>
        <form action="/topic/comment/complete" method="post" enctype="multipart/form-data">
          <input type="hidden" name="id" value="<?php echo $id?>">
          <input type="hidden" name="name" value="<?php if(empty($params['name'])){echo "匿名";}else{echo htmlspecialchars($params['name']);} ?>">
          <input type="hidden" name="comment" value="<?php echo $params['comment']?>">
          <input type="hidden" name="save_file_name" value="<?php echo $params['save_file_name']?>">
          <input type="hidden" name="csrf_name" value="<?php echo $csrf_name?>">
          <input type="hidden" name="csrf_value" value="<?php echo $csrf_value?>">
          <button type="submit" class="btn btn-primary buffer">　コメントを投稿する　</button>
        </form>
      </div>
    </div>
  </div> <!-- /container -->
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="/js/bootstrap.min.js"></script>
  </body>
<?php include(__DIR__."/common/footer.html"); ?>
</html>
