<!DOCTYPE html>
<html lang="ja">
<?php include(__DIR__."/common/head.html"); ?>
  <body>
<?php include(__DIR__."/common/header.html"); ?>
  <div class="container">
    <div class="col-md-8 col-md-offset-2 white-box">
      <div class="row buffer buffer-side">
        <h4>エラー</h4>
        <hr></hr>
      </div>
      <div class="row buffer-side buffer">
        <p>エラーが発生しました。再度お試しください。</p>
      </div>
    </div>
  </div> <!-- /container -->
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="/js/bootstrap.min.js"></script>
  </body>
<?php include(__DIR__."/common/footer.html"); ?>
</html>
