<!DOCTYPE html>
<html lang="ja">
<?php include(__DIR__."/common/head.html"); ?>
  <body>
<?php include(__DIR__."/common/header.html"); ?>
  <div class="container col-md-8 col-md-offset-2 white-box">
    <div class="row buffer buffer-side">
      <h4>トピックを作成する</h4>
      <hr></hr>
    </div>
    <div class="row buffer buffer-side">
      <span class="btn btn-default col-md-3 col-xs-12 btn-sm buffer-right"><h5>１．トピック内容の入力</h5></span>
      <span class="btn btn-default col-md-3 col-xs-12 btn-sm buffer-right"><h5>２．トピック内容の確認</h5></span>
      <span class="btn btn-warning col-md-3 col-xs-12 btn-sm buffer-right"><h5>３．トピック投稿完了</h5></span>
    </div>
    <div class="row buffer buffer-side">
      <p>トピックを作成いただきありがとうございます。</p>
      <p>反映までに時間がかかる場合がありますことをご了承ください。</p>
    </div>
    <div class="row buffer buffer-side">
      <a class="btn btn-primary" href="/" role="button">TOPに戻る</a>
    </div>
  </div> <!-- /container -->
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="/js/bootstrap.min.js"></script>
  </body>
<?php include(__DIR__."/common/footer.html"); ?>
</html>
