<!DOCTYPE html>
<html lang="ja">
<?php include(__DIR__."/common/head.html"); ?>
  <body>
<?php include(__DIR__."/common/header.html"); ?>
  <div class="container col-md-8 col-md-offset-2 white-box">
    <div class="row buffer buffer-side">
      <h4>トピックを作成する</h4>
      <hr></hr>
    </div>
    <div class="row buffer buffer-side">
      <span class="btn btn-default col-md-3 col-xs-12 btn-sm buffer-right"><h5>１．トピック内容の入力</h5></span>
      <span class="btn btn-warning col-md-3 col-xs-12 btn-sm buffer-right"><h5>２．トピック内容の確認</h5></span>
      <span class="btn btn-default col-md-3 col-xs-12 btn-sm buffer-right"><h5>３．トピック投稿完了</h5></span>
    </div>
    <div class="row buffer buffer-side">
      <?php if(isset($params['save_file_name'])){ ?>
      <img src="/uploads/tmp/<?php echo $params['save_file_name']?>" width="200"></img>
      <?php } ?>
      <h3><?php echo htmlspecialchars($params['title'])?></h3>
      <hr>
      <p>1.<?php if(empty($params['name'])){echo "匿名";}else{echo htmlspecialchars($params['name']);} ?></p>
      <div><?php echo htmlspecialchars($params['comment'])?></div>
    </div>
    <div class="row buffer buffer-side">
      <form action="/topic/complete" method="post" enctype="multipart/form-data">
        <input type="hidden" name="id" value="<?php echo $id?>">
        <input type="hidden" name="title" value="<?php echo $params['title']?>">
        <input type="hidden" name="name" value="<?php if(empty($params['name'])){echo "匿名";}else{echo htmlspecialchars($params['name']);} ?>">
        <input type="hidden" name="comment" value="<?php echo $params['comment']?>">
        <input type="hidden" name="save_file_name" value="<?php echo $params['save_file_name']?>">
        <input type="hidden" name="csrf_name" value="<?php echo $csrf_name?>">
        <input type="hidden" name="csrf_value" value="<?php echo $csrf_value?>">
        <button type="submit" class="btn btn-primary">トピックを作成する</button>
      </form>
    </div>
  </div> <!-- /container -->
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="/js/bootstrap.min.js"></script>
  </body>
<?php include(__DIR__."/common/footer.html"); ?>
</html>
